# Simple workflow for building 11ty site and deploying to GitHub Pages
name: Build 11ty site and deploy to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_ENV: build
  BASE_URL: ${{ github.event.repository.name }}

jobs:
  # Single deploy job since we're just deploying
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install repo dependencies
        run: npm install
      - name: Build static assets to dist directory
        run: npm run build
      - name: list files in directory to confirm that build has occurred
        run: ls
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist directory
          path: "dist/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
